### ISSUE TITLE
[🐛]: Error compiling hello world 

### ISSUE THREAD

**Issue by jaredpar** [otterkit/otterkit-cobol#10]
**Describe the bug**
Attempting to compile a `"Hello World"` style program to see what the codegen would look like. 

**To Reproduce**
Created a file main.cob with the contents

```cobol
IDENTIFICATION DIVISION.
PROGRAM-ID. IDSAMPLE.
ENVIRONMENT DIVISION.
PROCEDURE DIVISION.
    DISPLAY 'HELLO WORLD'.
    STOP RUN.
```

Then ran `otterkit build main.cob` 

**Expected behavior**
Compile succeeded

**Actual behavior**
Compiler crashed 

```txt
> otterkit  build .\main.cob
Otterkit parsing error: C:\Users\jaredpar\temp\cobol\main.cob:1:0
Unexpected token: Missing source unit ID name (PROGRAM-ID, FUNCTION-ID, CLASS-ID...), the identification division header is optional but every source unit must still have an ID.

     |
   1 | PROGRAM-ID. IDSAMPLE.
     |        ~

Attempting recovery: Unexpected tokens will be ignored until a separator period or an anchor point is found
(Anchors: OPTIONS, ENVIRONMENT, DATA, PROCEDURE)

Otterkit parsing recovery: C:\Users\jaredpar\temp\cobol\main.cob:1:3
Parser recovered at the following anchor point: (Anchor: ".")

     |
   1 | PROGRAM-ID. IDSAMPLE.
     |           ~

Unhandled exception. System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Peek()
   at Otterkit.Analyzer.<Analyze>g__IDENTIFICATION|7_1() in /Users/ktlsf/Documents/GitHub/otterkit/src/OtterkitAnalyzer.cs:line 198
   at Otterkit.Analyzer.<Analyze>g__Source|7_0() in /Users/ktlsf/Documents/GitHub/otterkit/src/OtterkitAnalyzer.cs:line 116
   at Otterkit.Analyzer.Analyze(List`1 tokenList, String fileName) in /Users/ktlsf/Documents/GitHub/otterkit/src/OtterkitAnalyzer.cs:line 101
   at Otterkit.OtterkitCompiler.CommandLineArguments(String[] args) in /Users/ktlsf/Documents/GitHub/otterkit/src/OtterkitCompiler.cs:line 153
   at Otterkit.OtterkitCompiler.Main(String[] args) in /Users/ktlsf/Documents/GitHub/otterkit/src/OtterkitCompiler.cs:line 39
```

**Platform Information (please complete the following information):**
 - OS: Windows
 - OS Version 11 
 - CPU Architecture x64
- Otterkit version: 1.0.15-alpha

**Additional context**
I have effectively zero experience with COBOL. This could very well a simple PEBKAC problem. 

Mostly just curious about what the code gen strategy was and wanted to take a look at it.

**Comment by KTSnowy** [comment]
Hey @jaredpar, it seems that the codegen is currently broken. I found what the issue is and I'm going to make the commit to fix it and an update to Nuget so that you can check our codegen structure. This should take around 30 minutes.

The last error was the broken codegen, but the first two are actually because the test code is in free format and the compiler defaults to fixed format. To fix the parsing errors you need to specify the `--free` compiler option.

**Comment by KTSnowy** [comment]
@jaredpar, The latest commit [830458c](https://github.com/otterkit/otterkit/commit/830458c023a7af73314a29381b0e48ba63b335c3) should fix this issue for now, but this needs more work later to generate more parts of the language. Right now the codegen is a little limited, but the overall structure will remain the same.

Could you try doing the following steps to check if the codegen is working for you?

Install the project templates and update the compiler:
```
dotnet new install Otterkit.Templates::1.0.1-alpha

dotnet tool update --global Otterkit --version 1.0.35-alpha
```

Create a new project and run the build command:
```
otterkit new app

otterkit build -e main.cob --free
```

If it works, this should create a .otterkit folder which contains the built binary inside the "Build" folder and the C# project files inside the "OtterkitExport" folder.

**Comment by TriAttack238** [comment]
> Hey @jaredpar, it seems that the codegen is currently broken. I found what the issue is and I'm going to make the commit to fix it and an update to Nuget so that you can check our codegen structure. This should take around 30 minutes.

For future reference, could you please state what the problem was?

**Comment by KTSnowy** [comment]
@TriAttack238 The codegen was checking the current scope by searching for the identification, data and procedure keywords, this did work previously but was not ideal.

We later added a scope check to the token classifier but didn't update the codegen to use the new "TokenScope" values from each token. This broke the codegen and would cause it to loop until it hit the end of the token list and throw an exception by trying to access the "next" token (after the EOF token).

Changing the codegen to use the TokenScope values instead of the keywords fixed the issue.

**Comment by VenierSophie** [comment]
I have the same problem. Maybe a link with the encoding ?

**Comment by KTSnowy** [comment]
Hey @VenierSophie, what error did you get? I'll work on a fix for it.

Could you show us the command line options used as well?

**Comment by VenierSophie** [comment]
Here are the error messages. (and I'm on mac ;-)).
<img width="1372" alt="Capture d’écran 2023-03-22 à 20 19 07" src="https://user-images.githubusercontent.com/124275015/227013676-3bec4a46-b6e1-4ad6-a730-b57e087554b1.png">

**Comment by KTSnowy** [comment]
@VenierSophie How does the source code look like?

**Comment by KTSnowy** [comment]
Also, I would recommend to try the Nuget version for the hello world. The newest code in the main branch might not be working completely right now, but I'll work on a fix for it.

**Comment by KTSnowy** [comment]
@VenierSophie I found the cause of the issue, I'll commit fixes to it soon.

**Comment by KTSnowy** [comment]
Fixed, the latest code on the main branch should work with the hello world example in this issue.

**Comment by VenierSophie** [comment]
Great, thank you !

**Comment by GitMensch** [comment]
I guess this can be closed now ... and for the following:

> [...] the first two are actually because the test code is in free format and the compiler defaults to fixed format. To fix the parsing errors you need to specify the `--free` compiler option.

You may want to follow GnuCOBOL's latest features here, below others, which are not relevant for  a COBOL2023 only compiler it has three format states: `free` and `fixed` (specified on the command line) and `auto` depending on the first lines (just checking "Is there an expected indicator in col7 - is there "data" before?") - but that likely should be moved out a a separate issue, when closing this one.

**Comment by KTSnowy** [comment]
Yes this issue can be closed now.

> and `auto` depending on the first lines

Hey @GitMensch thanks for the suggestion, I haven't thought about that before. I'll work on implementing this as a default option when no explicit format is passed on the command line. This should also help improve the developer experience.

Also, since you're here I wanted to ask for your feedback on the new error message format we introduced with this PR: https://github.com/otterkit/otterkit/pull/17. This was inspired by Rust's error messages and related libraries.

**Comment by KTSnowy** [comment]
Hey @GitMensch, I wanted to let you know that I just implemented the `auto` source format detection as the default if the user didn't specify one. It seems to be working.
